apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-conf
  labels:
    name: prom-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'locust'
        scrape_interval: 2s
        static_configs:
          - targets: ['le-pod:9646']
      - job_name: 'looker'
        scrape_interval: 2s
        static_configs:
          - targets: ['[LOOKER HOST]:9810']
      - job_name: 'cloudwatch'
        scrape_interval: 2s
        static_configs:
          - targets: ['cloudwatch-pod:9106']
